### ISSUE TITLE
Name 'DLL_PATH' is not defined

### ISSUE THREAD

**Issue by laisnegautier** [opensim-org/conda-opensim#20]
Hello,

I've been reinstalling my whole Opensim and anaconda ecosystem and I've encountered this issue when trying to use the latest conda package of opensim (4.4).

## Configuration
- OS: Windows 11 x64
- Anaconda distribution: 2022.05 (https://repo.anaconda.com/archive/)
- Opensim software: 4.4 (normally not used at all for the conda package (?))
- Opensim conda package: 4.4
- Conda environment used: default one with python3.8 

## Issue description
1. I installed Anaconda as root/admin, it gave me no issue with installing and using the opensim conda package.
2. I needed to install Anaconda as user only, so I uninstalled the root version, made sure every environment path is gone, then reinstalled the distribution as a user. When reinstalling the opensim conda package, I got the following:
**NameError: name 'DLL_PATH' is not defined** from the file __init__.py of the conda package in my environment.

## Temporary workaround
I checked and the issue seems to be that **os.path.join(sys.prefix, 'conda')** is **c:\Users\user_name\anaconda3\envs\opensim\conda** which shouldn't be that since it doesn't exist because the conda executable is not environment-specific.
I replaced the line **os.add_dll_directory(DLL_PATH)** by **os.add_dll_directory("c:\\Users\\user_name\\anaconda3\\Library\\bin")** and now everything works perfectly.

However, I don't understand why the "DLL_PATH" is not defined.
Is this workaround the good way to resolve it? 

Thank you.

**Comment by aymanhab** [comment]
Thanks for reporting, what you did is reasonable, however a new package was uploaded to our staging account opensim_admin that should make this change unnecessary, please let us know if it works for you out of the box so we can update the opensim-org official version. Thank you
