### ISSUE TITLE
Provide packages for python 3.10 and 3.11 

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/conda-opensim#31]
due to upgrade on Apr 27 2023
https://medium.com/google-colab/colab-updated-to-python-3-10-27eb02daa162

**Comment by aymanhab** [comment]
For now, on a notebook, go Tools->Command Palette->Use Fallback Runtime (to get python 3.9) works

**Comment by aymanhab** [comment]
3.10 for linux has been posted on opensim-org and works out of the box with new google colab runtime. Appreciate another pair of eyes to test. 3.10 for windows is on the staging opensim_admin channel. 
Any interested parties to test would be appreciated: @AlbertoCasasOrtiz @nickbianco @carmichaelong

**Comment by AlbertoCasasOrtiz** [comment]
Working for me in Google collab 👍🏻

**Comment by jenhicks** [comment]
@aymanhab Can you share details about exactly what you'd like tested?

**Comment by aymanhab** [comment]
As of now only 3.10 packages are available for windows and linux. To test:
- Create environment with proper python version (3.9, 3.10, maybe try 3.11)
- Install from opensim-org channel
- Make sure correct package is pulled and that import opensim works as expected.

I will let you know when 3.11 is ready, and I have no way to build mac for now.
@carmichaelong

**Comment by aymanhab** [comment]
Package for 3.11 on linux has now been uploaded as well. Note that 3.11 requires numpy 1.23.* otherwise build conflicts arise on both windows and linux

**Comment by aymanhab** [comment]
Built and uploaded packages for osx with 3.10 and 3.11 but on the opensim_admin channel as I don't have access to any other macs to test on.

**Comment by carmichaelong** [comment]
On OSX 13.3.1 with an M1 Macbook Pro: 3.10 and 3.11 both work for me using something like:

```
conda create -n opensim_py311 python=3.11
conda activate opensim_py311
conda install -c opensim_admin opensim
```

**Comment by carmichaelong** [comment]
On Windows 10, 3.10 and 3.11 both work for me using something like:
```
conda create -n opensim_py311 python=3.11
conda activate opensim_py311
conda install numpy=1.23
conda install -c opensim-org opensim
```

Unlike the mac builds, the `numpy` package needed to be installed beforehand, or else the last line would pick up the wrong `opensim` package (the 3.8 package).

**Comment by carmichaelong** [comment]
Retested on Windows, and for both 3.10 and 3.11, it grabbed the right `opensim` version without needing the correct `numpy` installed first.

**Comment by aymanhab** [comment]
Awesome, thank you so much 🥇
