### ISSUE TITLE
Create packages for opensim 4.5 on all platforms

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/conda-opensim#35]

**Comment by aymanhab** [comment]
@carmichaelong any testing you can perform on the conda packages for 4.5, channel opensim_admin would be appreciate it before we move to the opensim-org channel, in particular the two osx variants (osx-64, osx-arm64) thank you

**Comment by carmichaelong** [comment]
Looking good to me. For both osx-64 and osx-arm64, tested 4 different environments:

1: create a python environment without a specified version (e.g., `conda create --name opensim45`), and then install opensim (`conda install -c opensim_admin opensim`). This finds the latest python possible (3.11).
2-4: create a python environment with a specified python version (e.g., `conda create --name opensim45_py39 python=3.9), and then install opensim `conda install -c opensim_admin opensim`). Repeat for python 3.10 and 3.11.

Then to confirm that it works, open `python`, and run the following commands and see if info about the model object is returned:
```
import opensim
m = opensim.Model()
m
```
