### ISSUE TITLE
A potential bug in conda opensim-moco 4.5.1 Win package dependencies 

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/conda-opensim#38]
Hi, I was trying to install the conda opensim-moco from opensim-org channel on a Windows machine and found that a few dependencies are redundant. I ended up with this error:
`opensim-moco 4.5.1  is not installable because it requires libgcc >=13 , which does not exist (perhaps a missing channel).`
![image](https://github.com/user-attachments/assets/bbe292b7-b196-4bbb-8aeb-ba24a95d5660)
If I'm not mistaken, the highlighted dependencies are Linux-specific, as they didn't exist for the 4.5.0 version.

Thank you.

**Comment by aymanhab** [comment]
Hello,
We moved to use opensim alone not opensim-moco for the 4.5.1 version,
please let us know if that works as expected. We will retire the
opensim-moco package soon.

**Comment by mrrezaie** [comment]
Thanks @aymanhab for your response. 
Yes, the opensim 4.5.1 version works well, and it has Moco; thanks a lot. 
Does the 4.5.1 Linux package have Moco, as well?

**Comment by aymanhab** [comment]
Indeed it does though missing tropter at the moment.
